<?php
	//----------------------- INPUT ELEMENTS -------------------//
	$ssFilter 		= $this->arrParam['ssFilter'];
	$name 			= $this->formText ( 'name', $this->Item['name'], array ('class' => 'txtlong') );
	$module			= $this->formText ( 'p_module', $this->Item['p_module'], array ('class' => 'txtmedium') );
	$controller		= $this->formText ( 'p_controller', $this->Item['p_controller'], array ('class' => 'txtmedium') );
	$action			= $this->formText ( 'p_action', $this->Item['p_action'], array ('class' => 'txtmedium') );
	
	
	$arrInput = array(
				//array('label' => 'Chọn ngôn ngữ','input' => $selectLanguages),
				array('label' => 'Tiêu đề','input' => $name),
				array('label' => 'Module','input' => $module),
				array('label' => 'Controller','input' => $controller),
				array('label' => 'Action','input' => $action),
			);
	
	//-------------------- SESSAGES ERROR ------------------
	if(count($this->messageError)>0){
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('admin-permission/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php echo $this->render('admin-permission/sublink/index.php');?>
	<?php echo $errors;?>

	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
		<fieldset class="adminform">
		<legend>Chi tiết</legend>
			<table class="adminformlist">
				<?php echo $this->partialLoop('row.php', $arrInput);?>
			</table>
		</fieldset>
	</div>
	<!-- END: 	CONTENT -->
</form>