<?php
	//Xay dung tim kiem
	$ssFilter 		= $this->arrParam['ssFilter'];
	$page = '';
	if(isset($this->arrParam['page'])){
		$page = '/page/' . $this->arrParam['page'];
	}
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');

	$lblName 		= $this->cmsLinkSort('Tiêu đề','p.name',$ssFilter,$this->imgUrl . '/admin',$action_link);
	
	$lblID 			= $this->cmsLinkSort('ID','p.id',$ssFilter,$this->imgUrl . '/admin',$action_link);
	
	$lblModule 		= $this->cmsLinkSort('Module','p.module',$ssFilter,$this->imgUrl . '/admin',$action_link);
	$lblController	= $this->cmsLinkSort('Controller','p.controller',$ssFilter,$this->imgUrl . '/admin',$action_link);
	$lblAction	= $this->cmsLinkSort('Action','p.action',$ssFilter,$this->imgUrl . '/admin',$action_link);
	
	$keywords = $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	
	//--------------------- SEARCH --------------------//
	
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	$btnSerach = $this->formButton('search-now','Tìm',array('onclick'=>"OnSubmitForm('" .$linkSearch . "')"));
	
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');
	$btnResetSerach = $this->formButton('clear-keywords','Xóa',array('onclick'=>"OnSubmitForm('" .$linkResetSearch ."')"));
	
	$strSearch = $keywords . ' ' . $btnSerach . ' ' . $btnResetSerach;
	
	$filter = new Zendvn_GetSystem();
	$module = $filter->getAll();
	$slbModule[0] = 'Tất cả các module';
	foreach ($module AS $key => $val){
		$slbModule[$key] = $key;
	}
	$linkSlbModule = $this->baseUrl($this->currentController . '/filter/type/p_module');
	$selectModule = $this->formSelect('p_module',$ssFilter['p_module'],array('onchange'=>"OnSubmitForm('" .$linkSlbModule ."')"),$slbModule);
	$strSearchRight = $selectModule;
?>
<form name="appForm" method="post" action="">
	<?php echo $this->render('admin-permission/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php echo $this->render('admin-permission/sublink/index.php');?>	

	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
		<div class="block_filter">
			<div class="fl">
				<?php echo $strSearch;?>
			</div>
			<div class="fr">
				<?php echo $strSearchRight;?>
			</div>
			<div class="clr"></div>
		</div>
		<table class="adminlist">
			<tr>
				<th width="20">#</th>
				<th width="20">
					<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
				</th>
				<th><?php echo $lblName;?></th>
				<th><?php echo $lblModule;?></th>
				<th><?php echo $lblController;?></th>
				<th><?php echo $lblAction;?></th>
				<th width="70">Control</th>
				<th width="34"><?php echo $lblID;?></th>
			</tr>
			<?php
				foreach ($this->Items as $key => $val){
					$id 			= $val['id'];
					$name 			= $val['name'];
					$module			= $val['module'];
					$controller		= $val['controller'];
					$action			= $val['action'];
					
					$linkEdit		= $this->baseUrl($this->currentController . '/edit/id/' . $id . $page);
					$btnEdit		= $this->cmsIconButton('Sửa', $this->imgUrl . '/admin/icon_edit.png', $linkEdit);
					
					$linkDelete		= $this->baseUrl($this->currentController . '/delete/id/' . $id . $page);
					$btnDelete		= $this->cmsIconButton('Xóa', $this->imgUrl . '/admin/publish_r.png', $linkDelete);
					
					$strIconButton 	= $btnEdit . ' ' . $btnDelete;
					
					$name 	= '<b><a href="' . $linkEdit . '">' . $name . '</a></b>';
					
					$cid 			= $this->formCheckbox('cid[]',$val['id']);
					
					$classRow = 'row1';
					if($key % 2 == 0)
						$classRow = 'row0';
					
			?>
			<tr class="<?php echo $classRow;?>">
				<td align="center"><?php echo $key + 1;?></td>
				<td align="center"><?php echo $cid;?></td>
				<td align="left"><?php echo $name;?></td>
				<td align="center"><?php echo $module;?></td>
				<td align="center"><?php echo $controller;?></td>
				<td align="center"><?php echo $action;?></td>
				<td align="center"><?php echo $strIconButton;?></td>
				<td align="center"><?php echo $id;?></td>
			</tr>
			<?php
				} 
			?>
			<tr class="tbl_footer">
				<td colspan="12">
					<div class="container">
						<div class="pagination">
							<?php
								$currentUrl = $this->baseUrl($this->currentController . '/index');
								echo $this->paginationControl($this->paginator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl)); 
							?>
						</div>
					</div>
				</td>
			</tr>
		</table>
		<div class="clr"></div>
	</div>
	<!-- END: 	CONTENT -->
</form>