<?php
	//Xay dung tim kiem
	$ssFilter 		= $this->arrParam['ssFilter'];
	$page = '';
	if(isset($this->arrParam['page'])){
		$page = '/page/' . $this->arrParam['page'];
	}
	$faqs_id = '';
	if(isset($this->arrParam['faqs_id'])){
		$page = '/faqs_id/' . $this->arrParam['faqs_id'];
	}
	$url = $page . $faqs_id;
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order' . $url);
	$lblName 		= $this->cmsLinkSort('Tên','gr.name',$ssFilter,$this->imgUrl . '/admin',$action_link);
	
	$lblID 			= $this->cmsLinkSort('ID','gr.id',$ssFilter,$this->imgUrl . '/admin',$action_link);
	$lblContent 	= $this->cmsLinkSort('Nội dung','gr.content',$ssFilter,$this->imgUrl . '/admin',$action_link);
	$lblDate	 	= $this->cmsLinkSort('Ngày gửi','gr.date',$ssFilter,$this->imgUrl . '/admin',$action_link);
	
	//----------------------- INPUT ELEMENTS -------------------//
	$lang_code		= $this->FaqsInfo['lang_code'];
	$name 			= $this->FaqsInfo['name'];
	$email 			= $this->FaqsInfo['email'];
	$title 			= $this->FaqsInfo['title'];
	$date 			= $this->FaqsInfo['date'];
	$hits 			= $this->FaqsInfo['hits'];
	$id 			= $this->FaqsInfo['id'];
	
	$status 		= $this->FaqsInfo['status'];
	if($status == 1){
		$status = $this->cmsIconButton('Đang được hiển thị', $this->imgUrl . '/admin/tick.png');
	}else{
		$status = $this->cmsIconButton('Đã tắt hiển thị', $this->imgUrl . '/admin/publish_x.png');
	}
	
	$order 			= $this->FaqsInfo['order'];
	$selectCategory	= $this->FaqsInfo['category_name'];
	
	$content 		= htmlspecialchars_decode($this->FaqsInfo['content']);
	
	$arrFaqs = array(
			array('label' => 'Ngôn ngữ','input' => $lang_code),
			array('label' => 'Họ tên','input' => $name),
			array('label' => 'Email','input' => $email),
			array('label' => 'Thuộc danh mục','input' => $selectCategory),
			array('label' => 'Hiển thị','input' => $status),
			array('label' => 'Thứ tự','input' => $order),
			array('label' => 'Ngày gửi','input' => $date),
			array('label' => 'Lượt xem','input' => $hits),
			array('label' => '<b>Tiêu đề</b>','input' => $title),
			array('label' => '<b>Nội dung</b>','input' => $content, 'cols' => 2, 'style' => 'padding-top: 0;'),
	);
	
	$keywords = $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	$btnSerach = $this->formButton('search-now','Tìm',array('onclick'=>"OnSubmitForm('" .$linkSearch . "')"));
	
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');
	$btnResetSerach = $this->formButton('clear-keywords','Xóa',array('onclick'=>"OnSubmitForm('" .$linkResetSearch ."')"));
	
	$strSearch = '';

	$strSearchRight = '';
	
?>
<form name="appForm" method="post" action="">
	<?php echo $this->render('admin-reply/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php echo $this->render('admin-reply/sublink/index.php');?>
	
	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
		<div class="width-40 fl">
			<fieldset class="adminform">
				<legend>Chi tiết câu hỏi</legend>
				<table class="adminformlist">
					<?php echo $this->partialLoop('row.php', $arrFaqs);?>
				</table>
			</fieldset>
		</div>
		<div class="width-60 fr">
			<fieldset class="adminform">
				<legend>Danh sách trả lời</legend>
				<table class="adminlist">
					<tr>
						<th width="20">#</th>
						<th width="20">
							<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
						</th>
						<th width="80"><?php echo $lblName;?></th>
						<th><?php echo $lblContent;?></th>
						<th width="80"><?php echo $lblDate;?></th>
						<th width="70">Control</th>
						<th width="34"><?php echo $lblID;?></th>
					</tr>
					<?php
						foreach ($this->Items as $key => $val){
							$id 			= $val['id'];
							$name 			= $val['name'];
							$email			= $val['email'];
							$date			= $val['date'];
							$content		= $val['content'];
							
							
							$linkInfo		= $this->baseUrl($this->currentController . '/info/id/' . $id . $url);
							$btnInfo		= $this->cmsIconButton('Xem thông tin', $this->imgUrl . '/admin/icon_info.png', $linkInfo);
							
							$linkEdit		= $this->baseUrl($this->currentController . '/edit/id/' . $id . $url);
							$btnEdit		= $this->cmsIconButton('Sửa', $this->imgUrl . '/admin/icon_edit.png', $linkEdit);
							
							$linkDelete		= $this->baseUrl($this->currentController . '/delete/id/' . $id . $url);
							$btnDelete		= $this->cmsIconButton('Xóa', $this->imgUrl . '/admin/publish_r.png', $linkDelete);
							
							$strIconButton 	= $btnEdit . ' ' . $btnDelete;
							
							$alias = '<p class="smallsub">(Alias: ' . $val['alias'] . ' )</p>';
							$name 	= '<b><a href="' . $linkEdit . '">' . $name . '</a></b>';
							
							$cid 			= $this->formCheckbox('cid[]',$val['id']);
							
							$classRow = 'row1';
							if($key % 2 == 0)
								$classRow = 'row0';
							
					?>
					<tr class="<?php echo $classRow;?>">
						<td align="center"><?php echo $key + 1;?></td>
						<td align="center"><?php echo $cid;?></td>
						<td align="center"><?php echo $name;?></td>
						<td align="left"><?php echo $content;?></td>
						<td align="center"><?php echo $date;?></td>
						<td align="center"><?php echo $strIconButton;?></td>
						<td align="center"><?php echo $id;?></td>
					</tr>
					<?php
						} 
					?>
					<tr class="tbl_footer">
						<td colspan="12">
							<div class="container">
								<div class="pagination">
									<?php
										$faqs_id = '';
										if(isset($this->arrParam['faqs_id'])){
											$faqs_id = '/faqs_id/' . $this->arrParam['faqs_id'];
										}
										$currentUrl = $this->baseUrl($this->currentController . '/index' . $faqs_id);
										echo $this->paginationControl($this->paginator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl)); 
									?>
									<div class="limit"></div>
								</div>
							</div>
						</td>
					</tr>
				</table>
			</fieldset>
		</div>
		<div class="clr"></div>
	</div>
</form>