<?php
	//-------------------- SESSAGES ERROR ------------------
	if(count($this->messageError)>0){
		foreach ($this->messageError AS $key => $val){
			echo '<div class="listError" id="'.$key.'" rel="' . $val . '"></div>';
		}
	}
?>
<div class="block_thongTinTaiKhoan">
	<form name="appForm" method="post" action="" enctype="multipart/form-data">
		<div class="block_title">
			<?php echo $this->Title;?>
		</div>
		<div class="block_content">
			<?php
			$user_name = $this->Item['user_name'] . $this->formHidden('id',$this->Item['id']) . $this->formHidden('user_name',$this->Item['user_name']);
			$password_old = $this->formPassword('password_old','',array('class'=>'txtmedium')) . '<div class="view_error" id="view_password_old"></div>';
			$password = $this->formPassword('password','',array('class'=>'txtmedium')) . '<div class="view_error" id="view_password"></div>';
			$password_confirm = $this->formPassword('password_confirm','',array('class'=>'txtmedium')) . '<div class="view_error" id="view_password_confirm"></div>';
			?>
			<div class="note">
				<p class="">Vui lòng điền đầy đủ thông tin</p>
				<p>Những mục có dấu <span class="star">*</span> là bắt buộc phải nhập </p>
			</div>
			<div class="item">
				<div class="item_title">Thông tin đăng nhập</div>
				<div class="item_content">
					<table style="width: 100%">
						<tr>
							<td style="width: 150px;" class="label"><b>Email Đăng nhập (<span class="star">*</span>)</b></td>
							<td><?php echo $user_name;?></td>
						</tr>
						<tr>
							<td class="label"><b>Mật khẩu cũ (<span class="star">*</span>)</b></td>
							<td><?php echo $password_old;?></td>
						</tr>
						<tr>
							<td class="label"><b>Mật khẩu mới (<span class="star">*</span>)</b></td>
							<td><?php echo $password;?></td>
						</tr>
						<tr>
							<td class="label"><b>Xác nhận lại mật khẩu (<span class="star">*</span>)</b></td>
							<td><?php echo $password_confirm;?></td>
						</tr>
					</table>
				</div>
			</div>
			
			<div class="block_botton">
				<?php echo $this->formSubmit('btn_submit','Lưu',array('class'=>'user_button goc10'));?>
				<?php echo $this->formButton('btn_cancel','Đóng',array('class'=>'user_button goc10 mrl10', 'onclick' => "window.location.href = '".$this->baseUrl('default/user/index')."'"));?>
			</div>
			<div class="clr"></div>
		</div>
	</form>
	<script type="text/javascript">
		$("div.listError").each(function (i) {
	        //alert($(this).attr('rel'));
	        $('#view_' + $(this).attr('id')).html($(this).attr('rel'));
	    });
	</script>
</div>