<div class="memberRegistry">
	<div class="title">
		Thông báo từ hệ thống
	</div>
	<div class="registryForm" style="padding-left: 100px;">
		<p style="font-size: 16px; padding: 20px 0 10px; color: #1D437C;">
			Tài khoản của bạn vẫn chưa được kích hoạt sử dụng.
		</p>
		<p style="padding: 10px 0 3px;">(Vui lòng kiểm tra trong bulk mail hoặc spam mail của bạn nếu bạn không nhận được email trong hộp thư đến)</p>
		<p>(Trường hợp bạn không nhận được email kích hoạt vui lòng liên hệ: <span class="do"><?php echo $this->siteConfig['config_company']['hotline'];?></span> để được hỗ trợ.)</p>
	</div>
</div>