<?php
	//Xay dung tim kiem
	$ssFilter 		= $this->arrParam['ssFilter'];
	$page = '';
	if(isset($this->arrParam['page'])){
		$page = '/page/' . $this->arrParam['page'];
	}
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$lblName 		= $this->cmsLinkSort('Họ tên','i.full_name',$ssFilter,$this->imgUrl . '/admin',$action_link);
	
	$lblID 			= $this->cmsLinkSort('ID','i.id',$ssFilter,$this->imgUrl . '/admin',$action_link);
	
	$lblStatus 		= $this->cmsLinkSort('Status','i.status',$ssFilter,$this->imgUrl . '/admin',$action_link);
	$lblEmail 		= $this->cmsLinkSort('Email','i.email',$ssFilter,$this->imgUrl . '/admin',$action_link);
	$lblPhone	= $this->cmsLinkSort('Điện thoại','i.phone',$ssFilter,$this->imgUrl . '/admin',$action_link);
	$lblAddress	= $this->cmsLinkSort('Địa chỉ','i.address',$ssFilter,$this->imgUrl . '/admin',$action_link);
	$lblCreated	= $this->cmsLinkSort('Ngày gửi','i.created',$ssFilter,$this->imgUrl . '/admin',$action_link);
	
	$keywords = $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	$btnSerach = $this->formButton('search-now','Tìm',array('onclick'=>"OnSubmitForm('" .$linkSearch . "')"));
	
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');
	$btnResetSerach = $this->formButton('clear-keywords','Xóa',array('onclick'=>"OnSubmitForm('" .$linkResetSearch ."')"));
	
	$strSearch = $keywords . ' ' . $btnSerach . ' ' . $btnResetSerach;
	
	$strSearchRight = '';

?>
<form name="appForm" method="post" action="">
	<?php echo $this->render('admin-bill/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php echo $this->render('admin-bill/sublink/index.php');?>	

	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
		<div class="block_filter">
			<div class="fl">
				<?php echo $strSearch;?>
			</div>
			<div class="fr">
				<?php echo $strSearchRight;?>
			</div>
			<div class="clr"></div>
		</div>
		<table class="adminlist">
			<tr>
				<th width="20">#</th>
				<th width="43">
					<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
				</th>
				<th><?php echo $lblName;?></th>
				<th><?php echo $lblEmail;?></th>
				<th><?php echo $lblPhone;?></th>
				<th><?php echo $lblAddress;?></th>
				<th><?php echo $lblCreated;?></th>
				<th width="60"><?php echo $lblStatus;?></th>
				<th width="70">Control</th>
				<th width="34"><?php echo $lblID;?></th>
			</tr>
			<?php
				foreach ($this->Items as $key => $val){
					$id 			= $val['id'];
					$name 			= $val['full_name'];
					$email 			= $val['email'];
					$phone 			= $val['phone'];
					$address		= $val['address'];
					$created		= $val['created'];
						
					$status 		= $val['status'];
					if($status == 1){
						$linkStatus = $this->baseUrl($this->currentController . '/status/type/0/id/' . $id . $page);
						$status = $this->cmsIconButton('Kích vào để tắt', $this->imgUrl . '/admin/tick.png', $linkStatus);
					}else{
						$linkStatus = $this->baseUrl($this->currentController . '/status/type/1/id/' . $id . $page);
						$status = $this->cmsIconButton('Kích vào để bật', $this->imgUrl . '/admin/publish_x.png', $linkStatus);
					}
						
					$order 			= $this->formText('order[' . $val['id'] . ']', $val['order'], array('style'=>'width: 30px; text-align: center;'));
						
					$linkInfo		= $this->baseUrl($this->currentController . '/info/id/' . $id . $page);
					$btnInfo		= $this->cmsIconButton('Xem thông tin', $this->imgUrl . '/admin/icon_info.png', $linkInfo);
					
					$linkEdit		= $this->baseUrl($this->currentController . '/edit/id/' . $id . $page);
					$btnEdit		= $this->cmsIconButton('Sửa', $this->imgUrl . '/admin/icon_edit.png', $linkEdit);
						
					$linkDelete		= $this->baseUrl($this->currentController . '/delete/id/' . $id . $page);
					$btnDelete		= $this->cmsIconButton('Xóa', $this->imgUrl . '/admin/publish_r.png', $linkDelete);
						
					$strIconButton 	= $btnInfo . ' ' . $btnDelete;
					$name 	= '<a href="' . $linkInfo . '"><b>' . $name . '</b></a>';
					$cid 			= $this->formCheckbox('cid[]',$val['id']);
					
					$classRow = 'row1';
					if($key % 2 == 0)
						$classRow = 'row0';
						
			?>
			<tr class="<?php echo $classRow;?>">
				<td align="center"><?php echo $key + 1;?></td>
				<td align="center"><?php echo $cid;?></td>
				<td align="left"><?php echo $name;?></td>
				<td align="center"><?php echo $email;?></td>
				<td align="center"><?php echo $phone;?></td>
				<td align="center"><?php echo $address;?></td>
				<td align="center"><?php echo $created;?></td>
				<td align="center"><?php echo $status;?></td>
				<td align="center"><?php echo $strIconButton;?></td>
				<td align="center"><?php echo $id;?></td>
			</tr>
			<?php
				} 
			?>
			<tr class="tbl_footer">
				<td colspan="12">
					<div class="container">
						<div class="pagination">
							<?php
								$currentUrl = $this->baseUrl($this->currentController . '/index');
								echo $this->paginationControl($this->paginator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl)); 
							?>
							<div class="limit"></div>
						</div>
					</div>
				</td>
			</tr>
		</table>
		<div class="clr"></div>
	</div>
	<!-- END: 	CONTENT -->
</form>