<?php
	//Xay dung tim kiem
	$ssFilter 		= $this->arrParam['ssFilter'];
	$page = '';
	if(isset($this->arrParam['page'])){
		$page = '/page/' . $this->arrParam['page'];
	}
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order');
	$lblUserName 	= $this->cmsLinkSort('Tên thành viên','u.user_name',$ssFilter,$this->imgUrl . '/admin',$action_link);
	
	$lblID 			= $this->cmsLinkSort('ID','u.id',$ssFilter,$this->imgUrl . '/admin',$action_link);
	
	$lblStatus 		= $this->cmsLinkSort('Status','u.status',$ssFilter,$this->imgUrl . '/admin',$action_link);
	$lblEmail 		= $this->cmsLinkSort('Email','u.email',$ssFilter,$this->imgUrl . '/admin',$action_link);
	$lblRegisterDate= $this->cmsLinkSort('Ngày đăng ký','u.register_date',$ssFilter,$this->imgUrl . '/admin',$action_link);
	$lblGroup		= $this->cmsLinkSort('Nhóm','group_name',$ssFilter,$this->imgUrl . '/admin',$action_link);
	
	$keywords = $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	
	//---------------------GROUP SELECTBOX --------------------//
	$linkSlbGroup = $this->baseUrl($this->currentController . '/filter/type/group');
	$options = $this->slbGroup;
	$slbGroup = $this->formSelect('group_id',$ssFilter['group_id'],array('onchange'=>"OnSubmitForm('" .$linkSlbGroup ."')"),$options);
	$selectGroup = 'Nhóm: ' . $slbGroup;
	
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	$btnSerach = $this->formButton('search-now','Tìm',array('onclick'=>"OnSubmitForm('" .$linkSearch . "')"));
	
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');
	$btnResetSerach = $this->formButton('clear-keywords','Xóa',array('onclick'=>"OnSubmitForm('" .$linkResetSearch ."')"));
	
	$strSearch = $keywords . ' ' . $btnSerach . ' ' . $btnResetSerach;
	
	$strSearchRight = $selectGroup;

?>
<form name="appForm" method="post" action="">
	<?php echo $this->render('admin-user/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php echo $this->render('admin-user/sublink/index.php');?>	

	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
		<div class="block_filter">
			<div class="fl">
				<?php echo $strSearch;?>
			</div>
			<div class="fr">
				<?php echo $strSearchRight;?>
			</div>
			<div class="clr"></div>
		</div>
		<table class="adminlist">
			<tr>
				<th width="20">#</th>
				<th width="20">
					<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
				</th>
				<th><?php echo $lblUserName;?></th>
				<th width="89"><?php echo $lblStatus;?></th>
				<th width="150"><?php echo $lblEmail;?></th>
				<th width="100"><?php echo $lblRegisterDate;?></th>
				<th width="120"><?php echo $lblGroup;?></th>
				<th width="90">Control</th>
				<th width="34"><?php echo $lblID;?></th>
			</tr>
			<?php
				foreach ($this->Items as $key => $val){
					$id 			= $val['id'];
					$user_name 		= $val['user_name'];
					$email 			= $val['email'];
					$register_date	= $val['register_date'];
					$group_name		= $val['group_name'];
					
					$status 		= $val['status'];
					if($status == 1){
						$linkStatus = $this->baseUrl($this->currentController . '/status/type/0/id/' . $id . $page);
						$status = $this->cmsIconButton('Kích vào để tắt', $this->imgUrl . '/admin/tick.png', $linkStatus);
					}else{
						$linkStatus = $this->baseUrl($this->currentController . '/status/type/1/id/' . $id . $page);
						$status = $this->cmsIconButton('Kích vào để bật', $this->imgUrl . '/admin/publish_x.png', $linkStatus);
					}
						
					$linkInfo		= $this->baseUrl($this->currentController . '/info/id/' . $id . $page);
					$btnInfo		= $this->cmsIconButton('Xem thông tin', $this->imgUrl . '/admin/icon_info.png', $linkInfo);
					
					$linkEdit		= $this->baseUrl($this->currentController . '/edit/id/' . $id . $page);
					$btnEdit		= $this->cmsIconButton('Sửa', $this->imgUrl . '/admin/icon_edit.png', $linkEdit);
					
					$linkDelete		= $this->baseUrl($this->currentController . '/delete/id/' . $id . $page);
					$btnDelete		= $this->cmsIconButton('Xóa', $this->imgUrl . '/admin/publish_r.png', $linkDelete);
					
					$strIconButton 	= $btnInfo . ' ' . $btnEdit . ' ' . $btnDelete;
					
					$user_name 	= '<a href="' . $linkEdit . '">' . $user_name . '</a>';
					
					$cid 			= $this->formCheckbox('cid[]',$val['id']);
					
					$classRow = 'row1';
					if($key % 2 == 0)
						$classRow = 'row0';
					
			?>
			<tr class="<?php echo $classRow;?>">
				<td align="center"><?php echo $key + 1;?></td>
				<td align="center"><?php echo $cid;?></td>
				<td align="left"><?php echo $user_name;?></td>
				<td align="center"><?php echo $status;?></td>
				<td align="center"><?php echo $email;?></td>
				<td align="center"><?php echo $register_date;?></td>
				<td align="center"><?php echo $group_name;?></td>
				<td align="center"><?php echo $strIconButton;?></td>
				<td align="center"><?php echo $id;?></td>
			</tr>
			<?php
				} 
			?>
			<tr class="tbl_footer">
				<td colspan="12">
					<div class="container">
						<div class="pagination">
							<?php
								$currentUrl = $this->baseUrl($this->currentController . '/index');
								echo $this->paginationControl($this->paginator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl)); 
							?>
						</div>
					</div>
				</td>
			</tr>
		</table>
		<div class="clr"></div>
	</div>
	<!-- END: 	CONTENT -->
</form>