<?php
	//----------------------- INPUT ELEMENTS -------------------//
	$user_name 		= $this->Item['user_name'];
	$alias	 		= $this->Item['alias'];
	if(!empty($this->Item['user_avatar'])){
		$user_avatar 	= FILE_URL . '/users/img100x100/' . $this->Item['user_avatar'];
		$user_avatar	= '<img src="' . $user_avatar . '"><br>' . $this->Item['user_avatar'];
	}
	$email 			= $this->Item['email'];
	$first_name 	= $this->Item['first_name'];
	$last_name 		= $this->Item['last_name'];
	$birthday 		= $this->Item['birthday'];
	$register_date 	= $this->Item['register_date'];
	$register_ip 	= $this->Item['register_ip'];
	$visited_date 	= $this->Item['visited_date'];
	$visited_ip 	= $this->Item['visited_ip'];
	
	$status 		= $this->Item['status'];
	if($status == 1){
		$status = $this->cmsIconButton('Kích vào để tắt', $this->imgUrl . '/admin/tick.png');
	}else{
		$status = $this->cmsIconButton('Kích vào để bật', $this->imgUrl . '/admin/publish_x.png');
	}
	
	$options = $this->slbGroup;
	$slbGroup = $this->Item['group_name'];
	
	$sign = htmlspecialchars_decode($this->Item['sign']);

	$arrInput = array(
				array(
						'label' => 'User name',
						'input' => $user_name
						),
				array('label' => 'Avatar','input' => $user_avatar, 'style' => 'margin-left: 151px;'),
				array('label' => 'Email','input' => $email),
				array('label' => 'Chọn nhóm','input' => $slbGroup),
				array('label' => 'First name','input' => $first_name),
				array('label' => 'Last name','input' => $last_name),
				array('label' => 'Birthday','input' => $birthday),
				array('label' => 'Ngày đăng ký','input' => $register_date),
				array('label' => 'IP đăng ký','input' => $register_ip),
				array('label' => 'Ngày chỉnh sửa','input' => $visited_date),
				array('label' => 'IP chỉnh sửa','input' => $visited_ip),
				array('label' => 'Hiển thị','input' => $status),
				array('label' => 'Bút danh','input' => $alias),
				array('label' => 'Chữ ký','input' => $sign, 'cols' => 2, 'style' => 'padding-top: 0;'),
			);
	
	//-------------------- SESSAGES ERROR ------------------
	if(count($this->messageError)>0){
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('admin-user/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php echo $this->render('admin-user/sublink/index.php');?>
	<?php echo $errors;?>

	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
		<fieldset class="adminform">
			<legend>Chi tiết</legend>
			<table class="adminformlist">
				<?php echo $this->partialLoop('row.php', $arrInput);?>
			</table>
		</fieldset>
	</div>
	<!-- END: 	CONTENT -->
</form>