<?php
	$module = $this->moduleSettings['module'];
	/* echo "<pre>";
	print_r($module);
	echo "</pre>"; */
	
	//----------------------- INPUT ELEMENTS -------------------//
	$countPage 		= $this->formText('countPage',$module['countPage'], array ('class' => 'txtshort'));
	$pageRange 		= $this->formText('pageRange',$module['pageRange'], array ('class' => 'txtshort'));
	$option 		= array('Không','Có');
	$showPrice 		= $this->formRadio('showPrice',$module['showPrice'],null,$option, ' ');
	$showVat 		= $this->formRadio('showVat',$module['showVat'],null,$option, ' ');
	$showTinhTrang 	= $this->formRadio('showTinhTrang',$module['showTinhTrang'],null,$option, ' ');
	$showAddCart	= $this->formRadio('showAddCart',$module['showAddCart'],null,$option, ' ');
	$showHuongDan	= $this->formRadio('showHuongDan',$module['showHuongDan'],null,$option, ' ');
	$showBaoHanh	= $this->formRadio('showBaoHanh',$module['showBaoHanh'],null,$option, ' ');
	$showVanChuyen	= $this->formRadio('showVanChuyen',$module['showVanChuyen'],null,$option, ' ');
	$showKhuyenMai	= $this->formRadio('showKhuyenMai',$module['showKhuyenMai'],null,$option, ' ');
	$showSynopsis 	= $this->formRadio('showSynopsis',$module['showSynopsis'],null,$option, ' ');
	$showTags 		= $this->formRadio('showTags',$module['showTags'],null,$option, ' ');
	$showMxh 		= $this->formRadio('showMxh',$module['showMxh'],null,$option, ' ');
	$showComment 	= $this->formRadio('showComment',$module['showComment'],null,$option, ' ');
	$checkComment 	= $this->formRadio('checkComment',$module['checkComment'],null,$option, ' ');
	$typeComment	= array(
			'default' => 'Thông thường',
			'facebook' => 'Facebook',
	);
	$typeComment	= $this->formSelect('typeComment',$module['typeComment'],array(),$typeComment);

	$arrConfigModule = array(
				array('label' => 'Số tin trên 1 trang','input' => $countPage),
				array('label' => 'Số trang hiển thị','input' => $pageRange),
				array('label' => 'Hiện thị giá bán','input' => $showPrice),
				array('label' => 'Thông báo VAT','input' => $showVat),
				array('label' => 'Tình trạng sản phẩm','input' => $showTinhTrang),
				array('label' => 'Hướng dẫn mua hàng','input' => $showHuongDan),
				array('label' => 'Cho phép đặt hàng','input' => $showAddCart),
				array('label' => 'Hiển thị bảo hành','input' => $showBaoHanh),
				array('label' => 'Hiển thị vận chuyển','input' => $showVanChuyen),
				array('label' => 'Hiển thị khuyến mãi','input' => $showKhuyenMai),
				array('label' => 'Hiển thị mô tả ngăn','input' => $showSynopsis, 'desc' => 'Khi xem chi tiết tin hoặc xem sản phẩm ở dạng danh sách'),
				array('label' => 'Hiển thị Tags','input' => $showTags),
				array('label' => 'Chia sẻ mạng xã hội','input' => $showMxh),
				array('label' => 'Cho phép bình luận','input' => $showComment),
				array('label' => 'Kiểm duyệt bình luận','input' => $checkComment),
				array('label' => 'Kiểu bình luận','input' => $typeComment),
			);
	
	//-------------------- SESSAGES ERROR ------------------
	if(isset($this->arrParam['type']) == 'ok'){
		$message = '<div class="message">Cập nhật dữ liệu thành công</div>';
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('admin-config/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php echo $this->render('admin-config/sublink/index.php');?>
	<?php echo $message;?>

	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
		<fieldset class="adminform">
			<legend>Cấu hình Module</legend>
			<table class="adminformlist">
				<?php echo $this->partialLoop('row.php', $arrConfigModule);?>
			</table>
		</fieldset>
	</div>
	<!-- END: 	CONTENT -->
</form>