<?php
	$number = 0;
	$idArray = '';
	if(isset($this->arrParam['type']) == 'multi-delete' && count($this->arrParam['cid']) > 0){
		$number = count($this->arrParam['cid']);
		$idArray = $this->formHidden('cid',implode(',', $this->arrParam['cid']));
	}else
	if(isset($this->arrParam['id'])){
		$number = 1;
	}
?>
<form name="appForm" method="post" action="">
	<?php echo $this->render('backlink/toolbar/index.php');?>
 	<div class="clr"></div>

	<!-- BEGIN: CONTENT -->
	<div id="element-box">
		<div class="t">
			<div class="t">
				<div class="t"></div>
			</div>
		</div>
		<div class="m">
			<!-- BEGIN: ELEMENT BOX -->
			<fieldset class="adminform">
				<legend>Chi tiết</legend>
				<br>
				<div id="errors">
					Có <span style="font-size: 16px; color: red;"><strong><?php echo $number;?></strong></span> dữ liệu sẽ được xóa. Bạn có chắc chắn muốn xóa thật không?
				</div>
				<?php echo $idArray;?>
			</fieldset>
			<!-- END: ELEMENT BOX -->
		</div>
		<div class="b">
			<div class="b">
				<div class="b"></div>
			</div>
		</div>
	</div>
	<!-- END: 	CONTENT -->
</form>