<?php
	//----------------------- INPUT ELEMENTS -------------------//
	$ssFilter 		= $this->arrParam['ssFilter'];
	$selectLanguages = $this->slbLanguages;
	$selectLanguages['*'] = 'Tất cả ngôn ngữ';
	$selectLanguages = $this->formSelect('lang_code',$ssFilter['lang_code'],array(),$selectLanguages);
	$name 			= $this->formText ('name', $this->Item['name'], array ('class' => 'txtlong active'));
	$yahoo 			= $this->formText ('yahoo', $this->Item['yahoo'], array ('class' => 'txtlong'));
	$skype 			= $this->formText ('skype', $this->Item['skype'], array ('class' => 'txtlong'));
	$email 			= $this->formText ('email', $this->Item['email'], array ('class' => 'txtlong'));
	$phone 			= $this->formText ('phone', $this->Item['phone'], array ('class' => 'txtlong'));
	$tel 			= $this->formText ('tel', $this->Item['tel'], array ('class' => 'txtlong'));
	
	$option 		= array('Không','Có');
	if(isset($this->Item['status'])){
		$trangthai = $this->Item['status'];
	}else{
		$trangthai = 1;
	}
	$status 		= $this->formRadio('status',$trangthai,null,$option, ' ');
	if(isset($this->Item['order'])){
		$order = $this->Item['order'];
	}else{
		$order = 255;
	}
	$order 			= $this->formText ('order', $order, array ('class' => 'txtshort' ) );
	
	$arrInput = array(
				array('label' => 'Chọn ngôn ngữ','input' => $selectLanguages),
				array('label' => 'Tên','input' => $name, 'desc' => '<span class="red">*</span>'),
				array('label' => 'Yahoo','input' => $yahoo),
				array('label' => 'Skype','input' => $skype),
				array('label' => 'Email','input' => $email),
				array('label' => 'Phone','input' => $phone),
				array('label' => 'Máy bàn','input' => $tel),
				array('label' => 'Hiển thị','input' => $status),
				array('label' => 'Thứ tự','input' => $order),
			);
	
	//-------------------- SESSAGES ERROR ------------------
	if(count($this->messageError)>0){
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('admin-support/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php echo $this->render('admin-support/sublink/index.php');?>
	<?php echo $errors;?>

	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
		<fieldset class="adminform">
			<legend>Chi tiết</legend>
			<table class="adminformlist">
				<?php echo $this->partialLoop('row.php', $arrInput);?>
			</table>
		</fieldset>
	</div>
	<!-- END: 	CONTENT -->
</form>