<?php
	//----------------------- INPUT ELEMENTS -------------------//
	$ssFilter 		= $this->arrParam['ssFilter'];
	$selectLanguages = $ssFilter['lang_code'] . $this->formHidden('lang_code',$ssFilter['lang_code']);
	$name 			= $this->formText ( 'name', $this->Item['name'], array ('class' => 'txtlong active') );
	$picture		= '<img src="' . $this->Item['picture'] . '" style="max-width:200px;">';
	$picture 		= $this->cmsUserFiles('picture', $this->Item['picture'], 'Chọn ảnh', 'images', $options = array('class' => 'txtfile') ) . '<br>' .$picture ;
	$url 			= $this->formText ( 'url', $this->Item['url'], array ('class' => 'txtlong active') );
	$option 		= array('Không','Có');
	if(isset($this->Item['status'])){
		$trangthai = $this->Item['status'];
	}else{
		$trangthai = 1;
	}
	$status 		= $this->formRadio('status',$trangthai,null,$option, ' ');
	
	if(isset($this->Item['order'])){
		$order = $this->Item['order'];
	}else{
		$order = 255;
	}
	$order 			= $this->formText ('order', $order, array ('class' => 'txtshort' ) );
	
	$selectCategory	= $this->cmsSelect('cat_id',$this->Item['cat_id'],$this->slbCategory,array('size'=>0,'style'=>'min-width:200px;'));
	
	$slbTarget = array(
			'_self' => 'Tại trang (_self)',
			'_blank'=> 'Cửa sổ mới (_blank)',
			'_top'=> 'Cửa sổ trên cùng (_top)',
			'_parent'=> 'Cửa sổ cha (_parent)',
	);
	$selectTarget = $this->formSelect('target',$this->Item['target'],array(),$slbTarget);
	
	$arrInput = array(
				array('label' => 'Tiêu đề','input' => $name, 'desc' => '<span class="red">*</span>'),
				array('label' => 'Hình ảnh','input' => $picture,'style' => 'margin-left: 152px;'),
				array('label' => 'Đích đến','input' => $selectTarget),
				array('label' => 'Liên kết','input' => $url, 'desc' => '<span class="red">*</span>'),
				array('label' => 'Vị trí','input' => '<div id="category">' . $selectCategory . '</div>'),
				array('label' => 'Hiển thị','input' => $status),
				array('label' => 'Thứ tự','input' => $order),
			);
	
	//-------------------- SESSAGES ERROR ------------------
	if(count($this->messageError)>0){
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('admin-link/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php echo $this->render('admin-link/sublink/index.php');?>
	<?php echo $errors;?>

	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
		<fieldset class="adminform">
			<legend>Chi tiết</legend>
			<table class="adminformlist">
				<?php echo $this->partialLoop('row.php', $arrInput);?>
			</table>
		</fieldset>
	</div>
	<!-- END: 	CONTENT -->
</form>