<?php

	//----------------------- INPUT ELEMENTS -------------------//
	$lang_code		= $this->FaqsInfo['lang_code'];
	$name 			= $this->FaqsInfo['name'];
	$email 			= $this->FaqsInfo['email'];
	$title 			= $this->FaqsInfo['title'];
	$date 			= $this->FaqsInfo['date'];
	$hits 			= $this->FaqsInfo['hits'];
	$id 			= $this->FaqsInfo['id'];
	
	$status 		= $this->FaqsInfo['status'];
	if($status == 1){
		$status = $this->cmsIconButton('Đang được hiển thị', $this->imgUrl . '/admin/tick.png');
	}else{
		$status = $this->cmsIconButton('Đã tắt hiển thị', $this->imgUrl . '/admin/publish_x.png');
	}
	
	$order 			= $this->FaqsInfo['order'];
	$selectCategory	= $this->FaqsInfo['category_name'];
	
	$content 		= htmlspecialchars_decode($this->FaqsInfo['content']);
	
	$arrFaqs = array(
			array('label' => 'Ngôn ngữ','input' => $lang_code),
			array('label' => 'Họ tên','input' => $name),
			array('label' => 'Email','input' => $email),
			array('label' => 'Thuộc danh mục','input' => $selectCategory),
			array('label' => 'Hiển thị','input' => $status),
			array('label' => 'Thứ tự','input' => $order),
			array('label' => 'Ngày gửi','input' => $date),
			array('label' => 'Lượt xem','input' => $hits),
			array('label' => '<b>Tiêu đề</b>','input' => $title),
			array('label' => '<b>Nội dung</b>','input' => $content, 'cols' => 2, 'style' => 'padding-top: 0;'),
	);

	//----------------------- INPUT ELEMENTS -------------------//
	$faqs_id		= $this->formHidden('faqs_id',$this->FaqsInfo['id']);	
	$content		= $this->formTextarea('content', $this->Item['content'],array('rows'=>6,'style' => 'width:99%;'));
	
	$arrInput = array(
				array('label' => 'Trả lời','input' => $content),
			);

	//-------------------- SESSAGES ERROR ------------------
	if(count($this->messageError)>0){
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('admin-reply/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php echo $this->render('admin-reply/sublink/index.php');?>
	<?php echo $errors;?>

	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
		<div class="width-40 fl">
			<fieldset class="adminform">
				<legend>Chi tiết câu hỏi</legend>
				<table class="adminformlist">
					<?php echo $this->partialLoop('row.php', $arrFaqs);?>
				</table>
			</fieldset>
		</div>
		<div class="width-60 fr">
			<fieldset class="adminform">
				<legend>Nội dung trả lời</legend>
				<table class="adminformlist">
					<?php echo $this->partialLoop('row.php', $arrInput);?>
				</table>
			</fieldset>
		</div>
		<div class="clr"></div>
	</div>
	<!-- END: 	CONTENT -->
</form>