<?php
	$module = $this->moduleSettings['module'];
	/* echo "<pre>";
	print_r($module);
	echo "</pre>"; */
	
	//----------------------- INPUT ELEMENTS -------------------//
	$countPage 		= $this->formText('countPage',$module['countPage'], array ('class' => 'txtshort'));
	$pageRange 		= $this->formText('pageRange',$module['pageRange'], array ('class' => 'txtshort'));
	$option 		= array('Không','Có');
	$showAuthor 	= $this->formRadio('showAuthor',$module['showAuthor'],null,$option, ' ');
	$showSynopsis 	= $this->formRadio('showSynopsis',$module['showSynopsis'],null,$option, ' ');
	$showTags 		= $this->formRadio('showTags',$module['showTags'],null,$option, ' ');
	$showMxh 		= $this->formRadio('showMxh',$module['showMxh'],null,$option, ' ');
	$showDate 		= $this->formRadio('showDate',$module['showDate'],null,$option, ' ');
	$showHits 		= $this->formRadio('showHits',$module['showHits'],null,$option, ' ');
	$showComment 	= $this->formRadio('showComment',$module['showComment'],null,$option, ' ');
	$checkComment 	= $this->formRadio('checkComment',$module['checkComment'],null,$option, ' ');
	$typeComment	= array(
			'default' => 'Thông thường',
			'facebook' => 'Facebook',
	);
	$typeComment	= $this->formSelect('typeComment',$module['typeComment'],array(),$typeComment);

	$arrConfigModule = array(
				array('label' => 'Số tin trên 1 trang','input' => $countPage),
				array('label' => 'Số trang hiển thị','input' => $pageRange),
				array('label' => 'Hiển thị tác giả','input' => $showAuthor, 'desc' => 'Khi xem chi tiết tin'),
				array('label' => 'Hiển thị mô tả ngăn','input' => $showSynopsis, 'desc' => 'Khi xem chi tiết tin'),
				array('label' => 'Hiển thị Tags','input' => $showTags),
				array('label' => 'Chia sẻ mạng xã hội','input' => $showMxh),
				array('label' => 'Hiển thị thời gian đăng','input' => $showDate),
				array('label' => 'Hiển thị lượt xem','input' => $showHits),
				array('label' => 'Cho phép bình luận','input' => $showComment),
				array('label' => 'Kiểm duyệt bình luận','input' => $checkComment),
				array('label' => 'Kiểu bình luận','input' => $typeComment),
			);
	
	//-------------------- SESSAGES ERROR ------------------
	if(isset($this->arrParam['type']) == 'ok'){
		$message = '<div class="message">Cập nhật dữ liệu thành công</div>';
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('admin-config/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php echo $this->render('admin-config/sublink/index.php');?>
	<?php echo $message;?>

	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
		<fieldset class="adminform">
			<legend>Cấu hình Module</legend>
			<table class="adminformlist">
				<?php echo $this->partialLoop('row.php', $arrConfigModule);?>
			</table>
		</fieldset>
	</div>
	<!-- END: 	CONTENT -->
</form>