<?php
	$linkStart 		= $this->currentUrl . '/page/' . $this->first;
	$linkPrevious 	= $this->currentUrl . '/page/' . $this->previous;
	$linkNext 		= $this->currentUrl . '/page/' . $this->next;
	$linkEnd 		= $this->currentUrl . '/page/' . $this->last;
	
	$current		= $this->current;
	$pageCount		= $this->pageCount;
	
	$strPage = '';
	foreach ($this->pagesInRange as $key){
		if( $this->current == $key ){
			$strPage .= '<span class="active">' . $key . '</span>';
		}else{
			$linkPage = $this->currentUrl . '/page/' . $key;
			$strPage .= '<span class="link"><a rel="nofollow" href="javascript:void(0);" onclick="loadPage(\'' . $linkPage . '\')" title="Page ' . $key . '">' . $key . '</a></span>';
		}
	}
	
	$page = 'Page ' . $this->current . ' Of ' . $this->last;
?>
<?php
	if($pageCount > 1){ 
?>
<div id="paging">
	<div>
		<?php
			if($current == $this->first)
			{ 
		?>
		
		<?php
			}else{ 
		?>
		<span class="start"><a rel="nofollow" href="javascript:void(0);" onclick="loadPage('<?php echo $linkStart;?>')" title="Start">Đầu</a></span>
		<span class="prev"><a rel="nofollow" href="javascript:void(0);" onclick="loadPage('<?php echo $linkPrevious;?>')" title="Prev">Lùi</a></span>
		<?php
			} 
		?>
		<?php echo $strPage;?>
		<?php
			if($current == $pageCount)
			{ 
		?>

		<?php
			}else{
		?>
		<span class="next"><a rel="nofollow" href="javascript:void(0);" onclick="loadPage('<?php echo $linkNext;?>')" title="Next">Tiếp</a></span>
		<span class="end"><a rel="nofollow" href="javascript:void(0);" onclick="loadPage('<?php echo $linkEnd;?>')" title="End">Cuối</a></span>
		<?php 
			}
		?>
		<div class="clr"></div>
	</div>
	<div class="clr"></div>
</div>
<?php
	} 
?>