<?php
	//----------------------- INPUT ELEMENTS -------------------//
	$ssFilter 		= $this->arrParam['ssFilter'];
	$code 			= $this->formText ('code', $this->Item['code'], array ('class' => 'txtshort'));
	$name 			= $this->formText ('name', $this->Item['name'], array ('class' => 'txtlong active'));
	//--------------------- SELECTBOX COUNTRY --------------------//
	$slbCountry = $this->formSelect('country_id',$this->Item['country_id'],array(),$this->slbCountries);
	$option 		= array('Không','Có');
	if(isset($this->Item['status'])){
		$trangthai = $this->Item['status'];
	}else{
		$trangthai = 1;
	}
	$status 		= $this->formRadio('status',$trangthai,null,$option, ' ');
	if(isset($this->Item['order'])){
		$order = $this->Item['order'];
	}else{
		$order = 255;
	}
	$order 			= $this->formText ('order', $order, array ('class' => 'txtshort' ) );
	
	$arrInput = array(
				array('label' => 'Mã','input' => $code),
				array('label' => 'Tên','input' => $name, 'desc' => '<span class="red">*</span>'),
				array('label' => 'Chọn quốc gia','input' => $slbCountry),
				array('label' => 'Hiển thị','input' => $status),
				array('label' => 'Thứ tự','input' => $order),
			);
	
	//-------------------- SESSAGES ERROR ------------------
	if(count($this->messageError)>0){
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('admin-city/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php echo $this->render('admin-city/sublink/index.php');?>
	<?php echo $errors;?>

	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
		<fieldset class="adminform">
			<legend>Chi tiết</legend>
			<table class="adminformlist">
				<?php echo $this->partialLoop('row.php', $arrInput);?>
			</table>
		</fieldset>
	</div>
	<!-- END: 	CONTENT -->
</form>