<?php
	//----------------------- INPUT ELEMENTS -------------------//
	$group_id		= $this->formHidden('group_id',$this->Item['group_id']);
	$status 		= $this->formHidden ( 'status', $this->Item['status']);
	$user_name		= $this->formHidden('user_name',$this->Item['user_name']);
	$user_name 		= $this->Item['user_name'] . $user_name . $group_id . $status;
	
	$password 			= $this->formPassword('password', '', array ('class' => 'txtmedium active'));
	$password_new 		= $this->formPassword('password_new', '', array ('class' => 'txtmedium'));
	$password_confirm	= $this->formPassword('password_confirm', '', array ('class' => 'txtmedium'));
	
	$arrInput = array(
				array('label' => 'Tài khoản','input' => $user_name),
				array('label' => 'Mật khẩu hiện tại','input' => $password),
				array('label' => 'Mật khẩu mới','input' => $password_new, 'desc' => 'Từ 6 - 32 ký tự'),
				array('label' => 'Nhập lại mật khẩu mới','input' => $password_confirm),
			);
	
	//-------------------- SESSAGES ERROR ------------------
	if(count($this->messageError)>0){
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
	
	if(isset($this->arrParam['save']) == 'ok'){
		$message = '<div class="message">Mật khẩu đã thay đổi thành công. Bạn cần thoát khỏi hệ thống và đăng nhập lại</div>';
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('admin-info/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php echo $this->render('admin-info/sublink/index.php');?>
	<?php echo $errors;?>
	<?php echo $message;?>

	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
		<fieldset class="adminform">
			<legend>Chi tiết</legend>
			<table class="adminformlist">
				<?php echo $this->partialLoop('row.php', $arrInput);?>
			</table>
		</fieldset>
	</div>
	<!-- END: 	CONTENT -->
</form>