<?php
	$moduleConfig = $this->arrParam['moduleConfig'];
	$urlOptionsCategory = array('module'=>'shopping','controller'=>'index','action'=>'category',
			'cid'=>$this->category['id'],
			'alias'=>$this->category['alias'],
	);
	$linkCategory = $this->url($urlOptionsCategory,'shop-category');
	$contentCategory = htmlspecialchars_decode($this->category['content']);
?>
<?php
	echo $this->blkProductManu('view2');
?>
<div class="module_shop">
	<div class="module_title clearfix">
		<span class="icon"></span> 
		<h1 class="title goc5"><a href="<?php echo $linkCategory;?>" title="<?php echo $this->category['name'];?>"><?php echo $this->category['name'];?></a></h1>
	</div>
	<div class="module_content">
		<div class="line180 pd10">
			<?php echo $contentCategory;?>
		</div>
		<ul class="products clearfix">
			<?php
			foreach ($this->Items as $key => $val){
				$name = $val['name'];
				$code = '';
				if($val['code'] != ''){
					$code = '<p class="code">'.$this->language['productMaSanPham'].': ' . $val['code'] . '</p>';
				}
				$picture = '<img class="img" src="' . $val['picture'] . '" alt="'.$val['name'].'"/>';
					
				$synopsis = nl2br($val['synopsis']);
				$units_money = $val['units_money'];
				$price = '';
				
				if($val['price'] != 0){
					$price = '<p class="price">'.$this->language['productGiaBan'].': <span class="value">'.Zend_Locale_Format::toNumber($val['price'],array('precision' => 0)) . ' ' . $units_money.'</span></p>';
				}else{
					$price = '<p class="price">'.$this->language['productGiaBan'].': <span class="value">'.$this->language['lienHe'].'</span></p>';
				}
				
				$selloff = '';
				if($val['selloff'] > 0){
					$selloff = '<p class="p_selloff"><span>' . $val['selloff'] . '%</span></p>';
				}
				
				$addCart = '';
				if($moduleConfig['showAddCart'] == 1){
					$linkCart = $this->baseUrl('shopping/public/add-item/id/' . $val['id']);
					$addCart = '<a href="'.$linkCart.'" title="'.$this->language['productDatHang'].' '.$name.'" class="addCart" rel="nofollow">'.$this->language['productDatHang'].'</a>';
				}
					
				$urlOptions = array (
						'module' => 'shopping',
						'controller' => 'index',
						'action' => 'detail',
						'tcat' => $val ['category_alias'],
						'title' => $val ['alias'],
						'cid' => $val ['cat_id'],
						'id' => $val ['id'] );
				$linkDetial = $this->url( $urlOptions, 'shop-detail' );
				
				$tooltip = '<div class=tooltip_title>'.$name.'</div><div class=tooltip_content><img class=img src=' . $val['picture'] . ' alt='.$val['name'].'/></div>';
			?>
				<li class="item">
					<div class="p_content">
						<div class="p_images">
							<a href="<?php echo $linkDetial;?>" title="<?php echo $name;?>" onmouseover="tooltip.show('<?php echo $tooltip;?>')" onmouseout="tooltip.hide()">
								<?php echo $picture;?>
							</a>
						</div>
						<h4 class="p_title"><a href="<?php echo $linkDetial;?>" title="<?php echo $name;?>"><?php echo $name;?></a></h4>
						<div class="p_price">
							<?php echo $price;?>
						</div>
						<p class="p_detail">
							<?php echo $addCart;?>
						</p>
						<?php echo $selloff;?>
					</div>
				</li>
			<?php
				} 
			?>
		</ul>
		<?php
			if(!empty($this->arrParam['cid'])){
					
				$urlOptionsCategory = array('module'=>'shopping','controller'=>'index','action'=>'category',
						'cid'=>$this->arrParam['cid'],
						'alias'=>$this->arrParam['alias'],
				);
				$currentUrl = $this->url($urlOptionsCategory,'shop-category');
			}else{
				$currentUrl = 'products.html';
			}
			echo $this->paginationControl($this->paginator,'Sliding','pagination-index.phtml',array('currentUrl'=>$currentUrl,'arrParam' => $this->arrParam)); 
		?>
		</div>
		<div class="module_bottom"></div>
	</div>